FROM fedora:26

RUN dnf install -y dnf-plugins-core make golang-github-cpuguy83-go-md2man && \
    dnf copr enable -y phracek/Modularity-testing-framework && \
    dnf install -y modularity-testing-framework
# no need to `dnf clean all` since we don't distribute this image

VOLUME /src
WORKDIR /src
# we don't need to create an unprivileged user for the test run
# since we have complete access to docker socket = root on host
CMD ["make", "test"]
