PHONY: .run .build .test

run:
	cd fedora && make run
	cd centos && make run
	cd rhel && make run

build:
	cd fedora && make build
	cd centos && make build
	cd rhel && make build

run:
	cd fedora && make test
	cd centos && make test
	cd rhel && make test
